import Head from "next/head";
import Image from "next/image";
import Articles, { Article } from "../components/Articles";
import styles from "../styles/Home.module.css";

interface HomeProps {
  articles: Article[];
}

export default function Home({ articles }: HomeProps) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Webdev</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Web Dev!</a>
        </h1>

        <Articles articles={articles} />
      </main>
    </div>
  );
}

export const getStaticProps = async () => {
  const data = await fetch(
    `https://jsonplaceholder.typicode.com/posts?_limit=6`
  );
  const articles = await data.json();

  return {
    props: {
      articles,
    },
  };
};
